signin/urls.py
from django.conf.urls import url

from . import views

app_name = 'signin'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^patient_signin/$', views.patient_signin, name='patient_signin'),
    url(r'^find_patient/$', views.find_patients, name='find_patient'),
    url(
        r'^check_appointments/$',
        views.check_appointments,
        name='check_appointments'
    ),
    url(r'^patient_form/$', views.patient_form, name='patient_form'),
    url(
        r'^patient_form_submit/$',
        views.patient_form_submit,
        name='patient_form_submit'
    ),
    url(r'^allergies/$', views.allergies, name='allergies'),
    url(
        r'^update_allergies/$',
        views.update_allergies,
        name='update_allergies'
    ),
    url(r'^exit/$', views.exit, name='exit'),
    url(r'^auth_redirect$', views.auth_redirect, name='auth_redirect'),
    url(r'^exit_page$', views.exit_page, name='exit_page'),
    url(
        r'^appointments/(?P<id>\d+?)$',
        views.appointments,
        name='appointments'
    ),
]

signin/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    drchrono_id = models.CharField(max_length=100)

signin/views.py
import re
import json
import requests
from datetime import datetime
from urllib import urlencode
import urlparse

from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.models import User
from django.template.defaulttags import register
from django.contrib.auth.decorators import login_required

from . import config
from .models import Profile


def index(request):
    '''login page for doctor'''

    query = {
        'redirect_uri': add_path_to_url(config.REDIRECT_BASE, config.REDIRECT),
        'response_type': 'code',
        'client_id': config.CLIENT_ID
    }
    url = add_path_to_url(config.BASE_URL, config.AUTH)
    DRCHRONO_REDIRECT = add_query_to_url(url, query)

    return render(
        request,
        'signin/index.html',
        {'DRCHRONO_REDIRECT': DRCHRONO_REDIRECT}
    )


def auth_redirect(request):
    '''directs user to auth server login'''

    req_data = {
        'code': request.GET.get('code'),
        'grant_type': 'authorization_code',
        'redirect_uri': add_path_to_url(config.REDIRECT_BASE, config.REDIRECT),
        'client_id': config.CLIENT_ID,
        'client_secret': config.CLIENT_SECRET,
    }

    # Not using handle_api_request because we don't use
    # headers (access token) for this request
    response = requests.post(
        add_path_to_url(config.BASE_URL, config.TOKEN),
        data=req_data
    )
    data = response.json()
    request.session['access_token'] = data['access_token']
    handle_user(request, data['access_token'])
    return redirect('signin:patient_signin')


@login_required
def patient_signin(request):
    '''page for searching patients'''
    return render(request, 'signin/patient_signin.html')


@login_required
def find_patients(request):
    '''respond to POST request for patient info '''
    patients_data = get_patient_data(request)

    if patients_data:
        patient = patients_data[0]
    else:
        patient = None

    return JsonResponse(patient, safe=False)


@login_required
def check_appointments(request):
    '''redirects to appointments based on id '''

    patient_id = request.GET.get('appt_id')
    return redirect('signin:appointments', id=patient_id)


@login_required
def appointments(request, id):
    '''find appointments for given patient and current date '''

    appointment_data = get_appointment_data(request, id)
    data = transform_appointment_data(appointment_data["results"])
    return render(
        request,
        'signin/appointments.html',
        {"appointments": data, "patient_id": id}
    )


@login_required
def patient_form(request):
    '''provide form for patient data that is prepopulated '''
    patient_id = request.GET.get('patient_id')
    appt_id = request.GET.get('appt_id')
    patient = get_patient_by_id(request, patient_id)
    general, location, employer, contact = organize_forms()
    json_data = json.dumps(general + location + employer + contact)
    patient_json = json.dumps(patient)

    return render(
        request,
        'signin/patient_form.html',
        {
            'general': general,
            'location': location,
            'employer': employer,
            'contact': contact,
            'patient': patient,
            "json_data": json_data,
            'patient_json': patient_json,
            'appt_id': appt_id
        }
    )


@login_required
def patient_form_submit(request):
    ''' handles form submission and updates patient information'''
    data = request.POST.copy()

    for key, value in data.iteritems():
        if 'phone' in key:
            data[key] = format_phone_number(value)

    url = add_path_to_url(config.BASE_URL, config.PATIENTS, data['patient_id'])
    response = handle_api_request(
        request=request,
        verb='patch',
        url=url,
        data=data
    )
    return HttpResponse('success')


@login_required
def allergies(request):
    '''Load patient allergy information'''

    patient = request.GET.get('patient')
    appt_id = request.GET.get('appt_id')

    response = handle_api_request(
        request=request,
        verb='get',
        url=add_path_to_url(config.BASE_URL, config.ALLERGIES),
        params={'patient': patient}
    )

    response.raise_for_status()
    allergies = response.json()
    allergy_types, reactions = get_allergy_categories()

    return render(
        request,
        'signin/allergies.html',
        {
            'allergies': allergies['results'],
            'allergy_types': allergy_types,
            'reactions': reactions,
            'patient_id': patient,
            'appt_id': appt_id,
            'allergies_json': json.dumps(allergies['results'])
        }
    )


@login_required
def update_allergies(request):
    '''Takes updated allergy information and saves to current
    current appointment notes.
    '''
    data = request.POST.copy()

    allergies_now_inactive = request.POST.getlist('set_inactive[]')
    new_allergies = json.loads(request.POST.get('new_allergies', ""))
    new_allergies_list = [
        allergy['reaction'] + ": " + allergy['notes']
        for allergy in new_allergies
    ]
    new_allergies_text = '. '.join(new_allergies_list)

    if allergies_now_inactive:
        inactive_allergies = ', '.join(allergies_now_inactive)
        updated_note = 'Inactive Allergies: %s. ' % inactive_allergies
    else:
        updated_note = ""

    if new_allergies:
        updated_note = updated_note + new_allergies_text

    url = add_path_to_url(
        config.BASE_URL,
        config.APPOINTMENTS,
        data['appointment_id']
    )

    response = handle_api_request(
        request=request,
        verb='patch',
        url=url,
        data={'notes': updated_note}
    )
    return HttpResponse(str(len(new_allergies)))


@login_required
def exit(request):
    '''Changes patient status to 'Arrived' and redirects to
    exit page
    '''
    appt_id = request.GET.get('appt_id')

    url = add_path_to_url(config.BASE_URL, config.APPOINTMENTS, appt_id)
    response = handle_api_request(
        request=request,
        verb='patch',
        url=url,
        data={'status': 'Arrived'}
    )

    return redirect('signin:exit_page')

    return render(
        request,
        'signin/exit.html'
    )

def exit_page(request):
    '''testing new exit page'''
    return render(request, 'signin/exit.html')

# helper functions
def add_query_to_url(url, query):
    '''accepts url and dict and returns encoded url'''

    url_parts = list(urlparse.urlparse(url))
    url_parts[4] = urlencode(query)
    return urlparse.urlunparse(url_parts)


def add_path_to_url(url, *path):
    '''accepts url and path and returns encoded url'''

    url_parts = list(urlparse.urlparse(url))
    url_parts[2] = url_parts[2] + '/'.join([end for end in path])
    return urlparse.urlunparse(url_parts)


def format_phone_number(s):
    '''takes a variety of phone formats and returns in
    (XXX) XXX-XXXX format and appends an optional extension
    number.
    '''
    phone_pattern = re.compile(r'''
                # don't match beginning of string, number can start anywhere
    (\d{3})     # area code is 3 digits (e.g. '800')
    \D*         # optional separator is any number of non-digits
    (\d{3})     # trunk is 3 digits (e.g. '555')
    \D*         # optional separator
    (\d{4})     # rest of number is 4 digits (e.g. '1212')
    \D*         # optional separator
    (\d*)       # extension is optional and can be any number of digits
    $           # end of string
    ''', re.VERBOSE)

    try:
        if not phone_pattern.search(s):
            raise PhoneError("Inputted string didn't match")

        phone_num_groups = phone_pattern.search(s).groups()

        phone_text = '(%s) %s-%s' % (
            phone_num_groups[0],
            phone_num_groups[1],
            phone_num_groups[2]
        )

        if phone_num_groups[3]:
            phone_text = phone_text + ' x' + phone_num_groups[3]
    except PhoneError:
        return s

    return phone_text

class PhoneError(Exception):
    pass

def organize_forms():
    '''Returns patient fields in selected groupings'''

    return config.general, config.location, config.employer, config.contact


def transform_appointment_data(data):
    '''Adds AM and PM time format to each object '''
    for appointment in data:
        appointment['start_time'] = convert_time_to_str(
            appointment['scheduled_time']
        )

    return data


def get_user_data(request):
    '''Returns user(doctor's) information '''

    response = handle_api_request(
        request=request,
        verb='get',
        url=add_path_to_url(config.BASE_URL, config.CURRENT_USER)
    )
    data = response.json()
    return data


def get_appointment_data(request, patient_id):
    '''Returns appointment data for current day '''

    params = {
        'date': '-'.join([
            str(datetime.now().year),
            str(datetime.now().month),
            str(datetime.now().day)
        ]),
        'patient': patient_id
    }
    response = handle_api_request(
        request=request,
        verb='get',
        url=add_path_to_url(config.BASE_URL, config.APPOINTMENTS),
        params=params
    )

    data = response.json()
    return data


def handle_user(request, access_token):
    '''During Authorization process, create user
    if they don't exist.
     '''

    user_data = get_user_data(request)
    #user_query = User.objects.filter(username=user_data['id'])
    profile_query = Profile.objects.filter(drchrono_id=user_data['id'])

    if not profile_query:
        user = User.objects.create_user(username=str(user_data['username']))
        user.save()

        profile = Profile(user=user, drchrono_id=str(user_data['id']))
        profile.save()
    else:
        current_profile = profile_query[0]
        user = current_profile.user

    login(request, user)

signin/templates/signin/allergies.html
{% load static %}
<html>
<head>
  <title>Allgeries</title>
  <link rel="stylesheet" type"text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
  <link rel="stylesheet" type"text/css" href="{% static 'signin/css/allergies.css' %}" />

</head>
<body>

    <div class="allergies-main-container">

        <h1 class="page-header">Allergies</h1>

            <div class='allergies-form-container'>
                <div id="existing-allergy-container" class="patient-info">
                    <div class='allergy-header'>Existing Allergies</div>

                      {% if not allergies %}
                        <div id="no-allergies">Currently none</div>
                      {% endif %}
                      {% for a_allergy in allergies %}
                      <div class="allergy-item">

                        <div class="form-group row">
                          <label for="test" class="col-xs-4 col-form-label">Status</label>
                          <div class="col-xs-8">
                              <select class="form-control" id="allergy-{{a_allergy.id}}">
                                <option value="active" selected>active</option>
                                <option value="inactive">inactive</option>
                              </select>

                          </div>
                        </div>

                        <div class="form-group row">
                          <label for="test" class="col-xs-4 col-form-label">Reaction</label>
                          <div class="col-xs-8">
                              <input class="form-control" type="text" value="{{ a_allergy.reaction }}" id="test" disabled>

                          </div>
                        </div>

                        <div class="form-group row">
                          <label for="test" class="col-xs-4 col-form-label">Notes</label>
                          <div class="col-xs-8">
                              <input class="form-control" type="text" value="{{ a_allergy.notes }}" id="test" disabled>
                          </div>
                        </div>

                      </div>
                    {% endfor %}
                  </div>

                  <div class='allergy-header'>New Allergies?</div>

                      <div class="allergy-item">

                        <div class="form-group row">
                          <label for="test" class="col-xs-4 col-form-label">Reaction</label>
                          <div class="col-xs-8">
                              <select id="reaction-to-add" class="form-control">
                                  <option value="">
                                {% for a_reaction in reactions %}
                                  <option value="{{a_reaction}}">{{a_reaction}}</option>
                                {% endfor %}
                              </select>
                          </div>
                        </div>

                        <div class="form-group row">
                          <label for="test" class="col-xs-4 col-form-label">Notes</label>
                          <div class="col-xs-8">
                              <input id="notes-to-add" class="form-control" type="text" value="" placeholder="Description" id="test">
                          </div>
                        </div>

                        <div class="add-allergy-container">
                          <button id="add-allergy" class="btn btn-primary btn-lg">Add Allergy</button>

                          <button id="exit-checkin" class="btn btn-success btn-lg">Finish Check-in</button>

                          <form class="allergiesForm" action="{% url 'signin:exit' %}" name="allergiesForm" method="get">
                              {% csrf_token %}
                              <input id="appointmentId" type="hidden" name="appt_id" value="{{ appt_id }}">
                              <input name='allergiesSubmit' type="submit" class="btn btn-success btn-lg" value="Finish Check-in">
                          </form>

                        </div>
                      </div>
                  </div>
                </div>
              </div>
    </div>

    <script type="text/javascript">
      var newAllergies = [];
      var patientId = '{{ patient_id }}';
      var allergiesSetInactive = [];
      var existingAllergies = {{ allergies_json|safe }};
      var appointmentId = "{{ appt_id }}";

    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="{% static 'signin/js/allergies.js' %}"></script>


</body>
</html>

signin/templates/signin/appointments.html
{% load static %}
<html>
<head>
  <title>Appointments</title>
  <link rel="stylesheet" type"text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
  <link rel="stylesheet" type"text/css" href="{% static 'signin/css/appointments.css' %}" />

</head>
<body>

    <div class="appointment-main-container col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1">

        <h1 class="page-header">Appointments</h1>

        <div class="appointment-list col-lg-8 col-lg-offset-2">
          {% for appointment in appointments %}
            <a href="{% url 'signin:patient_form' %}?appt_id={{ appointment.id }}&patient_id={{ patient_id }}" class="list-group-item">

              <h4 class="list-group-item-heading">Exam Room {{ appointment.exam_room }}</h4>
              <p class="list-group-item-text">
                 {{appointment.reason}} at {{appointment.start_time}}
              </p>
              <p class="list-group-item-text">

              </p>
            </a>
          {% endfor %}
        </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

</body>
</html>

signin/templates/signin/exit.html
{% load static %}
<html>
<head>
  <title>Thank You</title>
  <link rel="stylesheet" type"text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
  <link rel="stylesheet" type"text/css" href="{% static 'signin/css/index.css' %}" />
</head>
<body>

  <div class="login-container">
    <h1>You are now checked in. We will call you when it is time for your appointment. Thank you and have a nice day!</h1>
  </div>

<script type="text/javascript">

    setTimeout(
        function() {
            var urlElem = window.location;
            urlElem.pathname = '/signin/patient_signin'
            window.location.href = uflElem.href;
        },
        5000
    );

</script>
</body>
</html>

signin/templates/signin/index.html
{% load static %}
<html>
<head>
  <title>Patient Sign-in</title>
  <link rel="stylesheet" type"text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
  <link rel="stylesheet" type"text/css" href="{% static 'signin/css/index.css' %}" />
</head>
<body>

  <div class="login-container">
    <h1>Login into your <img class="drchrono_logo" src="https://upload.wikimedia.org/wikipedia/en/1/1d/Drchrono_logo.png"></img> patient sign-in</h1>

    <input class="btn btn-default btn-lg login" type="button" value="Login" onclick="location.href='{{ DRCHRONO_REDIRECT }}';" />
  </div>

</body>
</html>

signin/templates/signin/patient_form.html
{% load static %}
<html>
<head>
  <title>Patient Form</title>
  <link rel="stylesheet" type"text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
  <link rel="stylesheet" type"text/css" href="{% static 'signin/css/patient_form.css' %}" />

</head>
<body>

    <div class="patient-main-container">

        <h1 class="page-header">Patient Form</h1>
        <p class="form-message">Please update or fill in missing information</p>

        <div class='patient-form-container'>

            <div class="patient-form-info patient-info-general">
                <div class='subsection-header'>General</div>
                {% for field in general %}
                <div class="form-group row col-lg-6">
                  <label for="patient-{{ field }}" class="col-xs-4 col-form-label">{{ field|convert_to_title }}</label>
                  <div class="col-xs-8">
                      <input class="form-control" type="text" value="{{ patient|get_item:field }}" id="patient-{{ field }}">
                  </div>
                </div>
                {% endfor %}
            </div>

            <div class="patient-form-info patient-info-location">
                <div class='subsection-header'>Geographical</div>

                {% for field in location %}
                <div class="form-group row col-lg-6">
                  <label for="patient-{{ field }}" class="col-xs-4 col-form-label">{{ field|convert_to_title }}</label>
                  <div class="col-xs-8">
                    <input class="form-control" type="text" value="{{ patient|get_item:field }}" id="patient-{{ field }}">
                  </div>
                </div>
                {% endfor %}
            </div>

            <div class="patient-form-info patient-info-employer">
                <div class='subsection-header'>Employer</div>

                {% for field in employer %}
                <div class="form-group row col-lg-6">
                  <label for="patient-{{ field }}" class="col-xs-4 col-form-label">{{ field|convert_to_title }}</label>
                  <div class="col-xs-8">
                    <input class="form-control" type="text" value="{{ patient|get_item:field }}" id="patient-{{ field }}">
                  </div>
                </div>
                {% endfor %}
            </div>

            <div class="patient-form-info patient-info-contact">
                <div class='subsection-header'>Contact</div>

                {% for field in contact %}
                <div class="form-group row col-lg-6">
                  <label for="patient-{{ field }}" class="col-xs-4 col-form-label">{{ field|convert_to_title }}</label>
                  <div class="col-xs-8">
                    <input class="form-control" type="phone" value="{{ patient|get_item:field }}" id="patient-{{ field }}">
                  </div>
                </div>
                {% endfor %}
            </div>

            <div class="form-submit-container">
              <button id="form-submit" class="btn btn-primary btn-lg patient-form-submit">Submit</button>

              <form class="patientForm" action="{% url 'signin:allergies' %}" name="patientForm" method="get">
                  {% csrf_token %}
                  <input type="hidden" name="patient" value="{{patient.id}}">
                  <input type="hidden" name="appt_id" value="{{ appt_id }}">
                  <input name='patientFormSubmit' type="submit" class="btn btn-success btn-lg" value="Finish Check-in">
              </form>
            </div>
        </div>
    </div>

    <script type="text/javascript">
      var data = {{ json_data|safe }};
      var patientId = {{patient.id}};
      var doctorId = {{patient.doctor}};
      var patient_data = {{ patient_json|safe }};
      //var exit_url = "{% url 'signin:allergies' %}?patient=".concat(patient_id).concat("&appt_id=").concat("{{ appt_id }}");

    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="{% static 'signin/js/patient_form.js' %}"></script>


</body>
</html>

signin/templates/signin/patient_signin.html
{% load static %}
<html>
<head>
  <title>Patient Sign-in</title>
  <link rel="stylesheet" type"text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
  <link rel="stylesheet" type"text/css" href="{% static 'signin/css/signin.css' %}" />

</head>
<body>

    <div class="patient-main-container">

        <h1 class="page-header">Patient Sign-in</h1>

        <div class="container patient-signin-container col-lg-6 col-lg-offset-3">



                    <div class="id-container">

                        <div class='subsection-header'>Identification</div>
                            <div class="search-container">
                                <label for="InputFirstName">First Name</label>
                                <div class="input-group">
                                    <input type="text" class="form-control" name="InputFirstName" id="InputFirstName" placeholder="First Name" value='Yujin' required>
                                    <span class="input-group-addon"><span class="glyphicon glyphicon-zoom-in"></span></span>
                                </div>

                                <br>
                                <label for="InputLastName">Last Name</label>
                                <div class="input-group">
                                    <input type="text" class="form-control" name="InputLastName" id="InputLastName" placeholder="Last Name" value="Cho" required>
                                    <span class="input-group-addon"><span class="glyphicon glyphicon-zoom-in"></span></span>
                                </div>

                                <br>
                                <label for="DateofBirth">Date of Birth</label>
                                <div class="input-group">
                                    <input type="date" class="form-control" name="DateofBirth" id="DateofBirth" value="1988-09-10"required>
                                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                                </div>
                                <br>

                                <div class="btn-container">
                                    <button id="patient-signin-btn" type="button" class="btn btn-primary btn-lg">Search</button>
                                </div>
                            </div>

                            <div id="patient-not-found-alert" class="alert alert-warning patient-alert" role="alert">
                                Your information could not be found. If the information is correct, please  &nbsp
                                <button type="button" class="btn btn-default create-patient-btn">Create Account</button>
                            </div>

                            <div id="patient-found-alert" class="patient-alert" role="alert">

                                <div class='subsection-header'>Search Result</div>

                                <div id="patient-info">
                                    Not Available
                                </div>
                                <br>

                                <form class="apptForm" action="{% url 'signin:check_appointments' %}" name="apptForm" method="get">
                                    {% csrf_token %}
                                    <input id="appointmentId" type="hidden" name="appt_id" value="">
                                    <input type="submit" class="btn btn-success create-patient-btn btn-lg" value="Find Appointment">
                                </form>
                            </div>
                        </div>
                    </div>


        </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="{% static 'signin/js/manage_signin.js' %}"></script>

</body>
</html>