birthday/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('reminder.urls')),
    url(r'^signin/', include('signin.urls')),
    url(r'^admin/', admin.site.urls),
]

reminder/urls.py
from django.conf.urls import url

from . import views

app_name = 'reminder'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^birthdays/$', views.birthdays, name='birthdays'),
    url(r'^auth_redirect$', views.auth_redirect, name='auth_redirect'),
    url(r'^create_message$', views.create_message, name='create_message'),
    url(r'^logout$', views.user_logout, name='logout'),
]

signin/urls.py
from django.conf.urls import url

from . import views

app_name = 'signin'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^patient_signin/$', views.patient_signin, name='patient_signin'),
    url(r'^find_patient/$', views.find_patients, name='find_patient'),
    url(
        r'^check_appointments/$',
        views.check_appointments,
        name='check_appointments'
    ),
    url(r'^patient_form/$', views.patient_form, name='patient_form'),
    url(
        r'^patient_form_submit/$',
        views.patient_form_submit,
        name='patient_form_submit'
    ),
    url(r'^allergies/$', views.allergies, name='allergies'),
    url(
        r'^update_allergies/$',
        views.update_allergies,
        name='update_allergies'
    ),
    url(r'^exit/$', views.exit, name='exit'),
    url(r'^auth_redirect$', views.auth_redirect, name='auth_redirect'),
    url(r'^exit_page$', views.exit_page, name='exit_page'),
    url(
        r'^appointments/(?P<id>\d+?)$',
        views.appointments,
        name='appointments'
    ),
]

reminder/models.py
from __future__ import unicode_literals

from datetime import datetime

from django.utils.encoding import python_2_unicode_compatible
from django.contrib.auth.models import User
from django.db import models


@python_2_unicode_compatible
class Message(models.Model):
    user = models.ForeignKey(User, default=None)
    patient_id = models.IntegerField()
    creator_name = models.CharField(max_length=200, default='', null=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.creation_date.strftime('%Y-%m-%d') + str(self.patient_id)

reminder/views.py
import json
import requests
from datetime import datetime

from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect, render_to_response
from django.contrib.auth import login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from . import drchrono_config
from .models import Message

def index(request):
    DRCHRONO_REDIRECT = "https://drchrono.com/o/authorize/?redirect_uri=%s&response_type=code&client_id=%s" % (drchrono_config.REDIRECT_URI, drchrono_config.CLIENT_ID)
    return render(
        request,
        'reminder/index.html',
        {'DRCHRONO_REDIRECT': DRCHRONO_REDIRECT}
    )

def auth_redirect(request):
    code = request.GET.get('code')
    response = requests.post('https://drchrono.com/o/token/', data={
        'code': code,
        'grant_type': 'authorization_code',
        'redirect_uri': drchrono_config.REDIRECT_URI,
        'client_id': drchrono_config.CLIENT_ID,
        'client_secret': drchrono_config.CLIENT_SECRET,
    })
    response.raise_for_status()
    data = response.json()
    request.session['access_token'] = data['access_token']
    handle_user(request, data['access_token'])
    return redirect('reminder:birthdays')
    
@login_required
def birthdays(request):
    data = get_patient_data(request.session['access_token'])
    recently_passed, upcoming = group_patients(request, data)
    
    if upcoming:
        current_patient = upcoming[0]
    else:
        current_patient = None



    return render(
        request, 
        'reminder/birthdays.html', 
        {
            'passed': recently_passed,
            'upcoming': upcoming,
            'patient_data': recently_passed + upcoming,
            'patient_data_json': json.dumps(recently_passed + upcoming)
        }
    )

@login_required
def create_message(request):
    current_user = request.user
    new_message = Message(
        user=current_user,
        patient_id = request.POST.get('patient_id')
    )
    new_message.save()
    return HttpResponse("Created Successfully")

def user_logout(request):
    logout(request)
    return redirect('reminder:index')



#Helper functions
def get_user_data(access_token):
    response = requests.get(
        'https://drchrono.com/api/users/current', 
        headers={
            'Authorization': 'Bearer %s' % access_token,
        }
    )
    response.raise_for_status()
    data = response.json()
    return data

def handle_user(request, access_token):
    user_data = get_user_data(access_token)
    user_query = User.objects.filter(username=user_data['id'])

    if not user_query:
        user = User.objects.create_user(username=str(user_data['id']))
        user.save()
    else:
        user = user_query[0]
    
    login(request, user)

def get_patient_data(access_token):
    headers = {
        'Authorization': 'Bearer %s' % access_token,
    }
    patients = []
    patients_url = 'https://drchrono.com/api/patients'
    
    while patients_url:
        data = requests.get(patients_url, headers=headers).json()
        patients.extend(data['results'])
        patients_url = data['next'] # A JSON null on the last page

    return patients

def filter_no_dob(data):
    return [
        patient for patient in data 
        if patient["date_of_birth"]
    ]

def add_msg_marker(request, data):
    for patient in data:
        recent_messages = Message.objects.filter(
            patient_id = patient['id'],
            user = request.user
        ).order_by('-creation_date')

        # shows if the most recent message from this doctor
        # to a patient is within 60 days
        if recent_messages:
            recent_message = recent_messages[0]
            current_date = get_currentdate(datetime.now())
            recent_message_date = get_currentdate(recent_message.creation_date)
            days_apart = (current_date - recent_message_date).days

            if abs(days_apart) <= 60:
                patient['msg_sent'] = True
            else:
                patient['msg_sent'] = False    
        else:
            patient['msg_sent'] = False

    return data

def get_currentdate(datetime_obj):
    date_now = datetime_obj
    return datetime(date_now.year, date_now.month, date_now.day)

def remove_unused_fields(data):
    # removing data we're not using
    
    patient_data = [
        get_reduced_dict(patient)
        for patient in data
    ]

    return patient_data

def get_reduced_dict(old_dict):
    new_dict = {}

    dict_keys = [
        'last_name',
        'id',
        'first_name', 
        'middle_name',
        'gender',
        'date_of_last_appointment',
        'doctor', 
        'date_of_birth', 
        'home_phone', 
        'email', 
        'patient_photo', 
        'office_phone', 
        'cell_phone'
    ]

    for new_key in dict_keys:
        new_dict[new_key] = old_dict[new_key]

    return new_dict

def transform_patient_data(request, data):
    patient_data = filter_no_dob(data)
    patient_data = remove_unused_fields(patient_data)
    patient_data = add_msg_marker(request, patient_data)
    return patient_data

def group_patients(request, patient_data):
    
    # Currently excluding patients without date of birth data
    #patient_data = add_msg_marker(request, filter_no_dob(patient_data))
    patient_data = transform_patient_data(request, patient_data)
    current_date = get_currentdate(datetime.now())
    
    recently_passed = []
    upcoming_birthdays = []

    #Determine appropriate date range for birthday greetings
    PAST_BDAY_RANGE = -14
    FUTURE_BDAY_RANGE = 60

    for patient in patient_data:
        bday = datetime.strptime(
            patient['date_of_birth'], '%Y-%m-%d'
        )
        bday_this_year = datetime(current_date.year, bday.month, bday.day)
        days_diff = bday_this_year - current_date

        # add days diff for sorting and display purposes
        if days_diff.days < 0 and days_diff.days >= PAST_BDAY_RANGE:
            patient['days_since_bday'] = days_diff.days
            recently_passed.append(patient)
        else:
            # if birthday already passed, add next year day diff
            if days_diff.days >= 0:
                patient['days_to_bday'] = days_diff.days
                
            else:
                bday_next_year = datetime(current_date.year + 1, bday.month, bday.day)
                days_to_bday = bday_next_year - current_date
                patient['days_to_bday'] = days_to_bday.days

            # only include if birthday is coming up in FUTURE_RANGE days
            if patient['days_to_bday'] <= FUTURE_BDAY_RANGE:
                upcoming_birthdays.append(patient)

    recently_passed.sort(key=lambda x: x['days_since_bday'], reverse=True)
    upcoming_birthdays.sort(key=lambda x: x['days_to_bday'])

    return recently_passed, upcoming_birthdays
    

reminder/templates/reminder/birthdays.html
{% load static %}
<html>
<head>
  <title>Birthday Reminder</title>
  <link rel="stylesheet" type"text/css" href="{% static 'reminder/css/bootstrap.css' %}" />
  <link rel="stylesheet" type"text/css" href="{% static 'reminder/css/stylesheet.css' %}" />


</head>
<body>


  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <img src="https://upload.wikimedia.org/wikipedia/en/1/1d/Drchrono_logo.png" id="brand-logo">
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                  <li>
                      <a href="{% url 'reminder:logout' %}">Logout</a>
                  </li>
              </ul>
          </div>
          <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
  </nav>

  

  <div id="main-container">

    
    <div class="patient-list col-lg-4 col-lg-offset-1 col-md-4 col-md-offset-1 col-sm-5 col-xs-12">      
      <div class='button-container'>
        <div class="btn-group" role="group" aria-label="past-or-upcoming">
          <button type="button" id="upcoming-btn" class="btn btn-default active">Upcoming</button>
          <button type="button" id="past-btn" class="btn btn-default">Past</button>
        </div>
      </div>


      <!-- Clickable menu for patients with upcoming birthdays -->
      <div class="list-group upcoming-group">
        
        {% for patient in upcoming %}
        <a href="#" class="list-group-item" id="{{ patient.id }}">

          <h4 class="list-group-item-heading">{{ patient.first_name }} {{ patient.middle_name}} {{ patient.last_name}} </h4>
          <p class="list-group-item-text">
            {% if patient.days_to_bday == 0 %}
              Birthday is today!
            {% else %}
              In {{ patient.days_to_bday }} day{{ patient.days_to_bday|pluralize}}
            {% endif %}
          </p>
          
          {% if patient.msg_sent %}
            <span class="glyphicon glyphicon-ok msg-sent" aria-hidden="true"></span>
          {% else %}
            <span class="glyphicon glyphicon-ok " aria-hidden="true"></span>
          {% endif %}

          
        </a>
        {% endfor %}
      </div>

      <!-- patients with recently passed birthdays -->
      <div class="list-group passed-group hide-group">
        
        {% for patient in passed %}
        <a href="#" class="list-group-item" id="{{ patient.id }}">
          <h4 class="list-group-item-heading">{{ patient.first_name }} {{ patient.middle_name}} {{ patient.last_name}} </h4>
          <p class="list-group-item-text">
              {{ patient.days_since_bday|stringformat:"+d"|slice:"1:" }} day{{ patient.days_since_bday|pluralize}} ago
          </p>

          {% if patient.msg_sent %}
            <span class="glyphicon glyphicon-ok msg-sent" aria-hidden="true"></span>
          {% else %}
            <span class="glyphicon glyphicon-ok " aria-hidden="true"></span>
          {% endif %}
          
        </a>
        {% endfor %}
      </div>

    </div>

    <div class="patient-container col-lg-6 col-md-6 col-sm-7 col-xs-12">
      
      {% for current_patient in patient_data %}
      <div class='patient-profile profile-hidden' id="profile-{{ current_patient.id }}">
        <h3>{{ current_patient.first_name }} {{ current_patient.last_name }}</h3>
        
        <div class="profile-pic-container col-xs-4 col-sm-12 col-md-3">
          <img src='{{ current_patient.patient_photo }}' class='profile-pic'></img>
        </div>
        <div class="patient-info col-xs-8 col-sm-6 col-md-4">
          <strong>Sex:</strong> {{ current_patient.gender }}
          <br>
          <strong>DOB:</strong> {{ current_patient.date_of_birth }}
          <br>
          <strong>Last Visit:</strong> {{ current_patient.date_of_last_appointment }}
        </div>

        <div class="patient-info col-xs-8 col-sm-6 col-md-5">
          <strong>Home:</strong> 
          {% if not current_patient.home_phone %}
            Missing
          {% else %}
            {{ current_patient.home_phone }}
          {% endif %}
          
          <br>
          <strong>Office:</strong> 
          {% if not current_patient.office_phone %}
            Missing
          {% else %}
            {{ current_patient.office_phone }}
          {% endif %}
          <br>
          <strong>Cell:</strong> 
          {% if not current_patient.cell_phone %}
            Missing
          {% else %}
            {{ current_patient.cell_phone }}
          {% endif %}
          <br>
          <strong>Email:</strong>
          {% if not current_patient.email %}
            Missing
          {% else %}
            {{ current_patient.email }}
          {% endif %}
        </div>

        <button type="button" id="greet-{{ current_patient.id }}" class="btn btn-default greetings-btn col-md-12 col-lg-12 col-sm-12 col-xs-12">Sent Greetings</button>

      </div>

      {% endfor %}



      <!--
      Maybe add communication functionality
      <div class="patient-communication">
        info on communication goes here
      </div>
      -->

    </div>

    

  </div>

  <script src="{% static 'reminder/js/jquery-3.1.0.min.js' %}"></script>
  <script src="{% static 'reminder/js/bootstrap.js' %}"></script>
  <script type="text/javascript">
    var patient_data = {{ patient_data_json|safe }};

    /*Set initial profile for viewing to be first on upcoming list*/
    var activeProfile = document.getElementById('profile-'.concat({{ upcoming.0.id }}));
    activeProfile.className = "patient-profile";
  </script>
  <script src="{% static 'reminder/js/manage_groups.js' %}"></script>
  

</body>
</html>

reminder/templates/reminder/index.html
{% load static %}
<html>
<head>
  <title>Birthday Reminder</title>
  <link rel="stylesheet" type"text/css" href="{% static 'reminder/css/bootstrap.css' %}" />
  <link rel="stylesheet" type"text/css" href="{% static 'reminder/css/stylesheet.css' %}" />
</head>
<body>

  <div class="login-container">
    <h1>Login into your <img id="drchrono_logo" src="https://upload.wikimedia.org/wikipedia/en/1/1d/Drchrono_logo.png"></img> birthday reminder</h1>

    <input class="btn btn-default btn-lg login" type="button" onclick="location.href='{{ DRCHRONO_REDIRECT }}';" value="Login" />
  </div>

</body>
</html>